<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Character;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $characters = [
            // Pyro
            [
                'name' => 'Arlecchino',
                'slug' => 'arlecchino',
                'element' => 'Pyro',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Arlecchino.png',
            ],
            [
                'name' => 'Hu Tao',
                'slug' => 'hu-tao',
                'element' => 'Pyro',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Hutao.png',
            ],
            [
                'name' => 'Yoimiya',
                'slug' => 'yoimiya',
                'element' => 'Pyro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Yoimiya.png',
            ],
            [
                'name' => 'Diluc',
                'slug' => 'diluc',
                'element' => 'Pyro',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Diluc.png',
            ],
            [
                'name' => 'Klee',
                'slug' => 'klee',
                'element' => 'Pyro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Klee.png',
            ],
            [
                'name' => 'Dehya',
                'slug' => 'dehya',
                'element' => 'Pyro',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Dehya.png',
            ],
            [
                'name' => 'Lyney',
                'slug' => 'lyney',
                'element' => 'Pyro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Liney.png',
            ],
            [
                'name' => 'Mavuika',
                'slug' => 'mavuika',
                'element' => 'Pyro',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Mavuika.png',
            ],
            [
                'name' => 'Bennett',
                'slug' => 'bennett',
                'element' => 'Pyro',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Bennett.png',
            ],
            [
                'name' => 'Xiangling',
                'slug' => 'xiangling',
                'element' => 'Pyro',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xiangling.png',
            ],
            [
                'name' => 'Chevreuse',
                'slug' => 'chevreuse',
                'element' => 'Pyro',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Chevreuse.png',
            ],
            [
                'name' => 'Gaming',
                'slug' => 'gaming',
                'element' => 'Pyro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Gaming.png',
            ],
            [
                'name' => 'Thoma',
                'slug' => 'thoma',
                'element' => 'Pyro',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Tohma.png',
            ],
            [
                'name' => 'Yanfei',
                'slug' => 'yanfei',
                'element' => 'Pyro',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Feiyan.png',
            ],
            [
                'name' => 'Amber',
                'slug' => 'amber',
                'element' => 'Pyro',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Ambor.png',
            ],
            [
                'name' => 'Xinyan',
                'slug' => 'xinyan',
                'element' => 'Pyro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xinyan.png',
            ],

            // Hydro
            [
                'name' => 'Furina',
                'slug' => 'furina',
                'element' => 'Hydro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Furina.png',
            ],
            [
                'name' => 'Neuvillette',
                'slug' => 'neuvillette',
                'element' => 'Hydro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Neuvillette.png',
            ],
            [
                'name' => 'Yelan',
                'slug' => 'yelan',
                'element' => 'Hydro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Yelan.png',
            ],
            [
                'name' => 'Kamisato Ayato',
                'slug' => 'kamisato-ayato',
                'element' => 'Hydro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Ayato.png',
            ],
            [
                'name' => 'Sangonomiya Kokomi',
                'slug' => 'sangonomiya-kokomi',
                'element' => 'Hydro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kokomi.png',
            ],
            [
                'name' => 'Tartaglia',
                'slug' => 'tartaglia',
                'element' => 'Hydro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Snezhnaya',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Tartaglia.png',
            ],
            [
                'name' => 'Nilou',
                'slug' => 'nilou',
                'element' => 'Hydro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Nilou.png',
            ],
            [
                'name' => 'Mona',
                'slug' => 'mona',
                'element' => 'Hydro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Mona.png',
            ],
            [
                'name' => 'Mualani',
                'slug' => 'mualani',
                'element' => 'Hydro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Mualani.png',
            ],
            [
                'name' => 'Sigewinne',
                'slug' => 'sigewinne',
                'element' => 'Hydro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Sigewinne.png',
            ],
            [
                'name' => 'Xingqiu',
                'slug' => 'xingqiu',
                'element' => 'Hydro',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xingqiu.png',
            ],
            [
                'name' => 'Barbara',
                'slug' => 'barbara',
                'element' => 'Hydro',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Barbara.png',
            ],
            [
                'name' => 'Candace',
                'slug' => 'candace',
                'element' => 'Hydro',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Candace.png',
            ],

            // Anemo
            [
                'name' => 'Kaedehara Kazuha',
                'slug' => 'kaedehara-kazuha',
                'element' => 'Anemo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kazuha.png',
            ],
            [
                'name' => 'Venti',
                'slug' => 'venti',
                'element' => 'Anemo',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Venti.png',
            ],
            [
                'name' => 'Xiao',
                'slug' => 'xiao',
                'element' => 'Anemo',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xiao.png',
            ],
            [
                'name' => 'Wanderer',
                'slug' => 'wanderer',
                'element' => 'Anemo',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Wanderer.png',
            ],
            [
                'name' => 'Xianyun',
                'slug' => 'xianyun',
                'element' => 'Anemo',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xianyun.png',
            ],
            [
                'name' => 'Jean',
                'slug' => 'jean',
                'element' => 'Anemo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Qin.png',
            ],
            [
                'name' => 'Chasca',
                'slug' => 'chasca',
                'element' => 'Anemo',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Chasca.png',
            ],
            [
                'name' => 'Sucrose',
                'slug' => 'sucrose',
                'element' => 'Anemo',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Sucrose.png',
            ],
            [
                'name' => 'Faruzan',
                'slug' => 'faruzan',
                'element' => 'Anemo',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Faruzan.png',
            ],
            [
                'name' => 'Lynette',
                'slug' => 'lynette',
                'element' => 'Anemo',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Linette.png',
            ],
            [
                'name' => 'Heizou',
                'slug' => 'shikanoin-heizou',
                'element' => 'Anemo',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Heizo.png',
            ],
            [
                'name' => 'Sayu',
                'slug' => 'sayu',
                'element' => 'Anemo',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Sayu.png',
            ],

            // Electro
            [
                'name' => 'Raiden Shogun',
                'slug' => 'raiden-shogun',
                'element' => 'Electro',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Shougun.png',
            ],
            [
                'name' => 'Yae Miko',
                'slug' => 'yae-miko',
                'element' => 'Electro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Yae.png',
            ],
            [
                'name' => 'Clorinde',
                'slug' => 'clorinde',
                'element' => 'Electro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Clorinde.png',
            ],
            [
                'name' => 'Cyno',
                'slug' => 'cyno',
                'element' => 'Electro',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Cyno.png',
            ],
            [
                'name' => 'Keqing',
                'slug' => 'keqing',
                'element' => 'Electro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Keqing.png',
            ],
            [
                'name' => 'Fischl',
                'slug' => 'fischl',
                'element' => 'Electro',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Fischl.png',
            ],
            [
                'name' => 'Kuki Shinobu',
                'slug' => 'kuki-shinobu',
                'element' => 'Electro',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Shinobu.png',
            ],
            [
                'name' => 'Beidou',
                'slug' => 'beidou',
                'element' => 'Electro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Beidou.png',
            ],
            [
                'name' => 'Kujou Sara',
                'slug' => 'kujou-sara',
                'element' => 'Electro',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Sara.png',
            ],
            [
                'name' => 'Razor',
                'slug' => 'razor',
                'element' => 'Electro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Razor.png',
            ],
            [
                'name' => 'Lisa',
                'slug' => 'lisa',
                'element' => 'Electro',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Lisa.png',
            ],
            [
                'name' => 'Dori',
                'slug' => 'dori',
                'element' => 'Electro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Dori.png',
            ],
            [
                'name' => 'Sethos',
                'slug' => 'sethos',
                'element' => 'Electro',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Sethos.png',
            ],

            // Dendro
            [
                'name' => 'Nahida',
                'slug' => 'nahida',
                'element' => 'Dendro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Nahida.png',
            ],
            [
                'name' => 'Alhaitham',
                'slug' => 'alhaitham',
                'element' => 'Dendro',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Alhatham.png',
            ],
            [
                'name' => 'Baizhu',
                'slug' => 'baizhu',
                'element' => 'Dendro',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Baizhuer.png',
            ],
            [
                'name' => 'Tighnari',
                'slug' => 'tighnari',
                'element' => 'Dendro',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Tighnari.png',
            ],
            [
                'name' => 'Kinich',
                'slug' => 'kinich',
                'element' => 'Dendro',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kinich.png',
            ],
            [
                'name' => 'Emilie',
                'slug' => 'emilie',
                'element' => 'Dendro',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Emilie.png',
            ],
            [
                'name' => 'Yaoyao',
                'slug' => 'yaoyao',
                'element' => 'Dendro',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Yaoyao.png',
            ],
            [
                'name' => 'Kirara',
                'slug' => 'kirara',
                'element' => 'Dendro',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Momoka.png',
            ],
            [
                'name' => 'Collei',
                'slug' => 'collei',
                'element' => 'Dendro',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Collei.png',
            ],
            [
                'name' => 'Kaveh',
                'slug' => 'kaveh',
                'element' => 'Dendro',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kaveh.png',
            ],

            // Cryo
            [
                'name' => 'Kamisato Ayaka',
                'slug' => 'kamisato-ayaka',
                'element' => 'Cryo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Ayaka.png',
            ],
            [
                'name' => 'Ganyu',
                'slug' => 'ganyu',
                'element' => 'Cryo',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Ganyu.png',
            ],
            [
                'name' => 'Wriothesley',
                'slug' => 'wriothesley',
                'element' => 'Cryo',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Wriothesley.png',
            ],
            [
                'name' => 'Shenhe',
                'slug' => 'shenhe',
                'element' => 'Cryo',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Shenhe.png',
            ],
            [
                'name' => 'Eula',
                'slug' => 'eula',
                'element' => 'Cryo',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Eula.png',
            ],
            [
                'name' => 'Qiqi',
                'slug' => 'qiqi',
                'element' => 'Cryo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Qiqi.png',
            ],
            [
                'name' => 'Citlali',
                'slug' => 'citlali',
                'element' => 'Cryo',
                'weapon_type' => 'Catalyst',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Citlali.png',
            ],
            [
                'name' => 'Aloy',
                'slug' => 'aloy',
                'element' => 'Cryo',
                'weapon_type' => 'Bow',
                'rarity' => 5,
                'region' => 'Other',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Aloy.png',
            ],
            [
                'name' => 'Diona',
                'slug' => 'diona',
                'element' => 'Cryo',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Diona.png',
            ],
            [
                'name' => 'Rosaria',
                'slug' => 'rosaria',
                'element' => 'Cryo',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Rosaria.png',
            ],
            [
                'name' => 'Layla',
                'slug' => 'layla',
                'element' => 'Cryo',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Sumeru',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Layla.png',
            ],
            [
                'name' => 'Charlotte',
                'slug' => 'charlotte',
                'element' => 'Cryo',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Charlotte.png',
            ],
            [
                'name' => 'Chongyun',
                'slug' => 'chongyun',
                'element' => 'Cryo',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Chongyun.png',
            ],
            [
                'name' => 'Freminet',
                'slug' => 'freminet',
                'element' => 'Cryo',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Freminet.png',
            ],
            [
                'name' => 'Mika',
                'slug' => 'mika',
                'element' => 'Cryo',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Mika.png',
            ],
            [
                'name' => 'Kaeya',
                'slug' => 'kaeya',
                'element' => 'Cryo',
                'weapon_type' => 'Sword',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kaeya.png',
            ],

            // Geo
            [
                'name' => 'Zhongli',
                'slug' => 'zhongli',
                'element' => 'Geo',
                'weapon_type' => 'Polearm',
                'rarity' => 5,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Zhongli.png',
            ],
            [
                'name' => 'Navia',
                'slug' => 'navia',
                'element' => 'Geo',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Navia.png',
            ],
            [
                'name' => 'Xilonen',
                'slug' => 'xilonen',
                'element' => 'Geo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Xilonen.png',
            ],
            [
                'name' => 'Chiori',
                'slug' => 'chiori',
                'element' => 'Geo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Fontaine',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Chiori.png',
            ],
            [
                'name' => 'Arataki Itto',
                'slug' => 'arataki-itto',
                'element' => 'Geo',
                'weapon_type' => 'Claymore',
                'rarity' => 5,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Itto.png',
            ],
            [
                'name' => 'Albedo',
                'slug' => 'albedo',
                'element' => 'Geo',
                'weapon_type' => 'Sword',
                'rarity' => 5,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Albedo.png',
            ],
            [
                'name' => 'Ningguang',
                'slug' => 'ningguang',
                'element' => 'Geo',
                'weapon_type' => 'Catalyst',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Ningguang.png',
            ],
            [
                'name' => 'Noelle',
                'slug' => 'noelle',
                'element' => 'Geo',
                'weapon_type' => 'Claymore',
                'rarity' => 4,
                'region' => 'Mondstadt',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Noel.png',
            ],
            [
                'name' => 'Yun Jin',
                'slug' => 'yun-jin',
                'element' => 'Geo',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Liyue',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Yunjin.png',
            ],
            [
                'name' => 'Gorou',
                'slug' => 'gorou',
                'element' => 'Geo',
                'weapon_type' => 'Bow',
                'rarity' => 4,
                'region' => 'Inazuma',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Gorou.png',
            ],
            [
                'name' => 'Kachina',
                'slug' => 'kachina',
                'element' => 'Geo',
                'weapon_type' => 'Polearm',
                'rarity' => 4,
                'region' => 'Natlan',
                'icon_url' => 'https://enka.network/ui/UI_AvatarIcon_Kachina.png',
            ],
        ];

        foreach ($characters as $char) {
            Character::updateOrCreate(
                ['slug' => $char['slug']],
                $char
            );
        }
    }
}
