<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Weapon;

class WeaponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $weapons = [
            // ─── SWORD (Bintang 5 & 4) ───────────────────────────────────
            [
                'name' => 'Mistsplitter Reforged',
                'slug' => 'mistsplitter-reforged',
                'type' => 'Sword',
                'rarity' => 5,
                'base_atk' => 674,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '44.1%',
                'passive_name' => "Mistsplitter's Edge",
                'passive_desc' => 'Gain a 12% Elemental DMG Bonus for all elements and receive the might of the Mistsplitter Emblem.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Narukami.png',
            ],
            [
                'name' => 'Primordial Jade Cutter',
                'slug' => 'primordial-jade-cutter',
                'type' => 'Sword',
                'rarity' => 5,
                'base_atk' => 542,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '44.1%',
                'passive_name' => 'Protector\'s Virtue',
                'passive_desc' => 'HP increased by 20%. Additionally, provides an ATK Bonus based on 1.2% of the wielder\'s Max HP.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Morax.png',
            ],
            [
                'name' => 'Splendor of Tranquil Waters',
                'slug' => 'splendor-of-tranquil-waters',
                'type' => 'Sword',
                'rarity' => 5,
                'base_atk' => 542,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '88.2%',
                'passive_name' => 'Dawn and Dusk on the Lake',
                'passive_desc' => 'When current HP increases or decreases, Elemental Skill DMG dealt is increased by 8% for 6s.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Regalis.png',
            ],
            [
                'name' => 'Freedom-Sworn',
                'slug' => 'freedom-sworn',
                'type' => 'Sword',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'Elemental Mastery',
                'sub_stat_value' => '198',
                'passive_name' => 'Revolutionary Chorale',
                'passive_desc' => 'A part of the "Millennial Movement" that wanders amidst the winds. Increases DMG by 10%.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Widsith.png',
            ],
            [
                'name' => 'Haran Geppaku Futsu',
                'slug' => 'haran-geppaku-futsu',
                'type' => 'Sword',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '33.1%',
                'passive_name' => 'Haidu Wavecrest',
                'passive_desc' => 'Obtain 12% All Elemental DMG Bonus.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Amenoma.png',
            ],
            [
                'name' => 'Favonius Sword',
                'slug' => 'favonius-sword',
                'type' => 'Sword',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '61.3%',
                'passive_name' => 'Windfall',
                'passive_desc' => 'CRIT hits have a 60% chance to generate Elemental Particles.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Zephyrus.png',
            ],
            [
                'name' => 'Sacrificial Sword',
                'slug' => 'sacrificial-sword',
                'type' => 'Sword',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '61.3%',
                'passive_name' => 'Composed',
                'passive_desc' => 'After damaging an opponent with an Elemental Skill, the skill has a 40% chance to end its own CD.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Fossil.png',
            ],
            [
                'name' => 'Amenoma Kageuchi',
                'slug' => 'amenoma-kageuchi',
                'type' => 'Sword',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'ATK%',
                'sub_stat_value' => '55.1%',
                'passive_name' => 'Iwakura Succession',
                'passive_desc' => 'After casting an Elemental Skill, gain 1 Succession Seed.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Sword_Bakufu.png',
            ],

            // ─── POLEARM (Bintang 5 & 4) ─────────────────────────────────
            [
                'name' => 'Staff of Homa',
                'slug' => 'staff-of-homa',
                'type' => 'Polearm',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '66.2%',
                'passive_name' => 'Reckless Cinnabar',
                'passive_desc' => 'HP increased by 20%. Additionally, provides an ATK Bonus based on 0.8% of the wielder\'s Max HP. When HP is less than 50%, this ATK bonus is increased by an additional 1% of Max HP.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Homa.png',
            ],
            [
                'name' => 'Primordial Jade Winged-Spear',
                'slug' => 'primordial-jade-winged-spear',
                'type' => 'Polearm',
                'rarity' => 5,
                'base_atk' => 674,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '22.1%',
                'passive_name' => 'Eagle Spear of Justice',
                'passive_desc' => 'On hit, increases ATK by 3.2% for 6s. Max 7 stacks.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Morax.png',
            ],
            [
                'name' => 'Engulfing Lightning',
                'slug' => 'engulfing-lightning',
                'type' => 'Polearm',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '55.1%',
                'passive_name' => 'Timeless Dream: Eternal Stove',
                'passive_desc' => 'ATK increased by 28% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80% ATK.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Narukami.png',
            ],
            [
                'name' => 'Crimson Moon\'s Semblance',
                'slug' => 'crimson-moons-semblance',
                'type' => 'Polearm',
                'rarity' => 5,
                'base_atk' => 674,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '22.1%',
                'passive_name' => 'Ashen Sun\'s Shadow',
                'passive_desc' => 'Grants a Bond of Life equal to 25% of Max HP when a Charged Attack hits an opponent.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_BloodMoon.png',
            ],
            [
                'name' => '"The Catch"',
                'slug' => 'the-catch',
                'type' => 'Polearm',
                'rarity' => 4,
                'base_atk' => 510,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '45.9%',
                'passive_name' => 'Shanty',
                'passive_desc' => 'Increases Elemental Burst DMG by 16% and Elemental Burst CRIT Rate by 6%.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Mori.png',
            ],
            [
                'name' => 'Dragon\'s Bane',
                'slug' => 'dragons-bane',
                'type' => 'Polearm',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Elemental Mastery',
                'sub_stat_value' => '221',
                'passive_name' => 'Bane of Flame and Water',
                'passive_desc' => 'Increases DMG against opponents affected by Hydro or Pyro by 20%.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Stardust.png',
            ],
            [
                'name' => 'Favonius Lance',
                'slug' => 'favonius-lance',
                'type' => 'Polearm',
                'rarity' => 4,
                'base_atk' => 565,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '30.6%',
                'passive_name' => 'Windfall',
                'passive_desc' => 'CRIT hits have a 60% chance to generate Elemental Particles.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Pole_Zephyrus.png',
            ],

            // ─── CLAYMORE (Bintang 5 & 4) ────────────────────────────────
            [
                'name' => 'Wolf\'s Gravestone',
                'slug' => 'wolfs-gravestone',
                'type' => 'Claymore',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'ATK%',
                'sub_stat_value' => '49.6%',
                'passive_name' => 'Wolfish Tracker',
                'passive_desc' => 'Increases ATK by 20%. On hitting opponents with less than 30% HP, increases all party members\' ATK by 40% for 12s.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Claymore_Wolfmound.png',
            ],
            [
                'name' => 'Redhorn Stonethresher',
                'slug' => 'redhorn-stonethresher',
                'type' => 'Claymore',
                'rarity' => 5,
                'base_atk' => 542,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '88.2%',
                'passive_name' => 'Gokadaiou Otogibanashi',
                'passive_desc' => 'DEF is increased by 28%. Normal and Charged Attack DMG is increased by 40% of DEF.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Claymore_Itto.png',
            ],
            [
                'name' => 'Verdict',
                'slug' => 'verdict',
                'type' => 'Claymore',
                'rarity' => 5,
                'base_atk' => 674,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '22.1%',
                'passive_name' => 'Many Oaths of Dawn and Dusk',
                'passive_desc' => 'Increases ATK by 20%. When party members obtain Elemental Shards from Crystallize reactions, the equipping character gains 1 Seal.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Claymore_GoldenCrucible.png',
            ],
            [
                'name' => 'Serpent Spine',
                'slug' => 'serpent-spine',
                'type' => 'Claymore',
                'rarity' => 4,
                'base_atk' => 510,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '27.6%',
                'passive_name' => 'Wavesplitter',
                'passive_desc' => 'Every 4s a character is on the field, they will deal 6% more DMG and take 3% more DMG.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Claymore_Kresnik.png',
            ],
            [
                'name' => 'Favonius Greatsword',
                'slug' => 'favonius-greatsword',
                'type' => 'Claymore',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '61.3%',
                'passive_name' => 'Windfall',
                'passive_desc' => 'CRIT hits have a 60% chance to generate Elemental Particles.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Claymore_Zephyrus.png',
            ],

            // ─── BOW (Bintang 5 & 4) ─────────────────────────────────────
            [
                'name' => 'Aqua Simulacra',
                'slug' => 'aqua-simulacra',
                'type' => 'Bow',
                'rarity' => 5,
                'base_atk' => 542,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '88.2%',
                'passive_name' => 'The Cleansing Form',
                'passive_desc' => 'HP is increased by 16%. When there are opponents nearby, the DMG dealt by the wielder of this weapon is increased by 20%.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Bow_Kirin.png',
            ],
            [
                'name' => 'Thundering Pulse',
                'slug' => 'thundering-pulse',
                'type' => 'Bow',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '66.2%',
                'passive_name' => 'Rule By Thunder',
                'passive_desc' => 'Increases ATK by 20% and grants the might of the Thunder Emblem.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Bow_Narukami.png',
            ],
            [
                'name' => 'Polar Star',
                'slug' => 'polar-star',
                'type' => 'Bow',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '33.1%',
                'passive_name' => 'Daylight\'s Augury',
                'passive_desc' => 'Elemental Skill and Elemental Burst DMG increased by 12%. Gain Ashen Nightstar stacks on hits.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Bow_Worldbane.png',
            ],
            [
                'name' => 'The Stringless',
                'slug' => 'the-stringless',
                'type' => 'Bow',
                'rarity' => 4,
                'base_atk' => 510,
                'sub_stat_type' => 'Elemental Mastery',
                'sub_stat_value' => '165',
                'passive_name' => 'Song of Flagrance',
                'passive_desc' => 'Increases Elemental Skill and Elemental Burst DMG by 24%.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Bow_Troupe.png',
            ],
            [
                'name' => 'Favonius Warbow',
                'slug' => 'favonius-warbow',
                'type' => 'Bow',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Energy Recharge',
                'sub_stat_value' => '61.3%',
                'passive_name' => 'Windfall',
                'passive_desc' => 'CRIT hits have a 60% chance to generate Elemental Particles.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Bow_Zephyrus.png',
            ],

            // ─── CATALYST (Bintang 5 & 4) ────────────────────────────────
            [
                'name' => 'Tome of the Eternal Flow',
                'slug' => 'tome-of-the-eternal-flow',
                'type' => 'Catalyst',
                'rarity' => 5,
                'base_atk' => 542,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '88.2%',
                'passive_name' => 'Aeon Wave',
                'passive_desc' => 'HP is increased by 16%. When current HP increases or decreases, Charged Attack DMG is increased by 14% for 4s.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Catalyst_Wheatley.png',
            ],
            [
                'name' => 'Kagura\'s Verity',
                'slug' => 'kaguras-verity',
                'type' => 'Catalyst',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '66.2%',
                'passive_name' => 'Kagura Dance',
                'passive_desc' => 'Gains the Kagura Dance effect when using an Elemental Skill, causing the Elemental Skill DMG to increase by 12% for 16s.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Catalyst_Narukami.png',
            ],
            [
                'name' => 'Lost Prayer to the Sacred Winds',
                'slug' => 'lost-prayer-to-the-sacred-winds',
                'type' => 'Catalyst',
                'rarity' => 5,
                'base_atk' => 608,
                'sub_stat_type' => 'CRIT Rate',
                'sub_stat_value' => '33.1%',
                'passive_name' => 'Boundless Blessing',
                'passive_desc' => 'Increases Movement SPD by 10%. When in battle, gain an 8% Elemental DMG Bonus every 4s. Max 4 stacks.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Catalyst_Fourwinds.png',
            ],
            [
                'name' => 'The Widsith',
                'slug' => 'the-widsith',
                'type' => 'Catalyst',
                'rarity' => 4,
                'base_atk' => 510,
                'sub_stat_type' => 'CRIT DMG',
                'sub_stat_value' => '55.1%',
                'passive_name' => 'Debut',
                'passive_desc' => 'When a character takes the field, they will gain a random theme song for 10s: Recitative (ATK), Aria (Elemental DMG), or Interlude (Elemental Mastery).',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Catalyst_Troupe.png',
            ],
            [
                'name' => 'Sacrificial Fragments',
                'slug' => 'sacrificial-fragments',
                'type' => 'Catalyst',
                'rarity' => 4,
                'base_atk' => 454,
                'sub_stat_type' => 'Elemental Mastery',
                'sub_stat_value' => '221',
                'passive_name' => 'Composed',
                'passive_desc' => 'After damaging an opponent with an Elemental Skill, the skill has a 40% chance to end its own CD.',
                'icon_url' => 'https://enka.network/ui/UI_EquipIcon_Catalyst_Fossil.png',
            ],
        ];

        foreach ($weapons as $w) {
            Weapon::updateOrCreate(
                ['slug' => $w['slug']],
                $w
            );
        }
    }
}
